In [ ]:
# Autograd (automatic diferentiation engine in PyTorch)
#is used in backprop step when training NN,
#we have to calculate the gradients to error in respect to other parameters

In [1]:
import torch

In [2]:
a = torch.tensor([5.],requires_grad = True)
b = torch.tensor([6.],requires_grad = True)

In [3]:
a


tensor([5.], requires_grad=True)

In [4]:
b

tensor([6.], requires_grad=True)

In [5]:
y = a**3 + b**2

In [6]:
y #Gradient function

tensor([161.], grad_fn=<AddBackward0>)

In [7]:
#Calculate gradients of a and b in respect to y

In [ ]:
# dy/da = 3*a**2 = 75
# dy/db = -2b = -12

In [8]:
print(a.grad)

None


In [9]:
y.backward()

In [11]:
a.grad

tensor([75.])

In [12]:
b.grad

tensor([12.])

In [13]:
W = torch.rand(10,1,requires_grad = True)

In [14]:
W

tensor([[0.3950],
        [0.6406],
        [0.3823],
        [0.5662],
        [0.0833],
        [0.0686],
        [0.1767],
        [0.7980],
        [0.1887],
        [0.8520]], requires_grad=True)

In [15]:
x = torch.rand(1,10) #input samples

In [16]:
x

tensor([[0.0649, 0.2473, 0.7646, 0.2659, 0.1103, 0.5788, 0.8297, 0.5765, 0.3521,
         0.0286]])

In [17]:
output = torch.matmul(x,W)+b

In [18]:
loss = 1- output

In [19]:
output

tensor([[7.3733]], grad_fn=<AddBackward0>)

In [20]:
loss.backward()

In [21]:
W.grad

tensor([[-0.0649],
        [-0.2473],
        [-0.7646],
        [-0.2659],
        [-0.1103],
        [-0.5788],
        [-0.8297],
        [-0.5765],
        [-0.3521],
        [-0.0286]])

In [22]:
with torch.no_grad():
    W = W + 0.001* W.grad.data

In [23]:
W

tensor([[0.3949],
        [0.6403],
        [0.3815],
        [0.5659],
        [0.0832],
        [0.0681],
        [0.1759],
        [0.7974],
        [0.1883],
        [0.8520]])

In [ ]:
# In each iteration we need to clear gradients and upadate weights and biases
# Before we do next iteration gradients should be set to zero, and that's usually done by optimizer