In [2]:
import torch
import numpy as np
#A PyTorch Tensor is basically the same as a numpy array: 
#it does not know anything about deep learning or computational graphs or gradients,
#and is just a generic n-dimensional array to be used for arbitrary numeric computation.

#The biggest difference between a numpy array and a PyTorch Tensor is that 
#a PyTorch Tensor can run on either CPU or GPU.
#To run operations on the GPU, just cast the Tensor to a cuda datatype.

In [44]:
torch.cuda.is_available()


False

In [45]:
some_data = [[1,2],[3,4]]

In [46]:
type(some_data)

list

In [47]:
np.array(some_data)

array([[1, 2],
       [3, 4]])

In [48]:
np.asarray(some_data)

array([[1, 2],
       [3, 4]])

In [49]:
some_data = torch.tensor(some_data) #convert to torch tensor

In [50]:
type(some_data)


torch.Tensor

In [51]:
some_data.dtype

torch.int64

In [52]:
#Convert numpy array to torch tensor
numpy_arr = np.random.rand(3,4)
numpy_arr


array([[0.76804644, 0.01975541, 0.37755108, 0.21293448],
       [0.42267216, 0.82271487, 0.73579505, 0.57362243],
       [0.06299159, 0.87226725, 0.05798243, 0.78041817]])

In [53]:
torch.from_numpy(numpy_arr)

tensor([[0.7680, 0.0198, 0.3776, 0.2129],
        [0.4227, 0.8227, 0.7358, 0.5736],
        [0.0630, 0.8723, 0.0580, 0.7804]], dtype=torch.float64)

In [54]:
#Same result
torch.tensor(numpy_arr)

tensor([[0.7680, 0.0198, 0.3776, 0.2129],
        [0.4227, 0.8227, 0.7358, 0.5736],
        [0.0630, 0.8723, 0.0580, 0.7804]], dtype=torch.float64)

In [55]:
torch.ones(3,4) #creates torch tensor with ones same as numpy function

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [56]:
my_tensor = torch.rand(3,4)

In [5]:
m = torch.zeros(3,4)
m[:,1:3]= torch.ones(3,2)
print(m)

tensor([[0., 1., 1., 0.],
        [0., 1., 1., 0.],
        [0., 1., 1., 0.]])


In [58]:
#Move to GPU
#my_tensor = my_tensor.to("cuda")
my_tensor.device

device(type='cpu')

In [59]:
#select all the rows from column 1 and two same as numpy
my_tensor[:,1:3]

tensor([[0.6650, 0.9026],
        [0.2051, 0.7370],
        [0.3090, 0.6151]])

In [60]:
my_tensor.mul(my_tensor) #multiply element wise

tensor([[0.9442, 0.4422, 0.8147, 0.1937],
        [0.6835, 0.0421, 0.5432, 0.5214],
        [0.3497, 0.0955, 0.3783, 0.0841]])

In [61]:
my_tensor* my_tensor #multiply element wise

tensor([[0.9442, 0.4422, 0.8147, 0.1937],
        [0.6835, 0.0421, 0.5432, 0.5214],
        [0.3497, 0.0955, 0.3783, 0.0841]])

In [62]:
#Matrix multiplication
my_tensor.matmul(my_tensor.T)

tensor([[2.3948, 1.9228, 1.4629],
        [1.9228, 1.7902, 1.2151],
        [1.4629, 1.2151, 0.9076]])

In [63]:
#Same
my_tensor @ my_tensor.T

tensor([[2.3948, 1.9228, 1.4629],
        [1.9228, 1.7902, 1.2151],
        [1.4629, 1.2151, 0.9076]])

In [66]:
my_tensor = torch.ones(5,4)
my_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [67]:
my_tensor.sum(axis = 1)

tensor([4., 4., 4., 4., 4.])

In [68]:
#torch.max torch.min 
torch.max(my_tensor)

tensor(1.)

In [70]:
#concatenate
torch.cat([my_tensor,my_tensor],dim=1)

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [72]:
torch.nn.functional.softmax(my_tensor,dim=0) #softmax apply on every element in every column

tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]])

In [73]:
my_tensor.shape

torch.Size([5, 4])

In [75]:
my_tensor.size(0)

5

In [76]:
# we are dealing with this kind of tensors batchSize, numOfChannels,rows,cols
torch.rand(10,3,128,128).size()

torch.Size([10, 3, 128, 128])

In [78]:
#Pragovanje sve ispod prve vrednosti se pretvara u nju. Sve iznad druge vrednosti se pretvara u nju
my_tensor = torch.rand(3,4)
my_tensor.clip(0.2,0.8)

tensor([[0.7149, 0.8000, 0.2534, 0.8000],
        [0.7412, 0.7633, 0.2000, 0.3319],
        [0.8000, 0.8000, 0.4286, 0.7222]])

In [ ]:
#Convert to numpy
my_tensor.cpu().detach().numpy()